### ISSUE TITLE
[BE-4] Whole of the HospitalManagementDB development. [EPIC]

### ISSUE THREAD

**Issue by AnilKOC** [Ridvansezen/Hospital_Management_System#6]
[BE-4] Whole of the HospitalManagementDB development.

This is EPIC issue, you need to select an DB schema.
After, need to be configure and develop of the DB.

Database normalizations rules is must required!

Tips: Share the DB schema into this issue.

**Comment by Ridvansezen** [comment]
![db_schema](https://github.com/Ridvansezen/Hospital_Management_System/assets/111904621/6cda33ac-0e2c-4855-a04b-ccf2c157fb01)

Here is the DB diagram of the project.

@AnilKOC

**Comment by AnilKOC** [comment]
We could develope this schema via django's orm.
